---
title: "scImpute Updates"
author: "Wei Vivian Li"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
#output: pdf_document
---


## Updates

> 2018/08/15:

-   Version 0.0.9 is released!
-   More robust implementation of dimension reduction.
-   Faster calculation of cell similarity.

> 2018/06/27:

-   Version 0.0.8 is released!
-   Faster implementation of dimension reduction.

> 2018/06/08:

-   Version 0.0.7 is released!
-   New option for application on TPM values.

> 2018/03/16:

 + Version 0.0.6 is released!
 + The scImpute method is published at [*Nature Communications*](https://www.nature.com/articles/s41467-018-03405-7).
 + scImpute now supports input and output in the format of R objects (.rds).
 
> 2018/01/12:

 + Version 0.0.5 is released!
 + It is now possible to apply scImpute on just one cell population by setting `Kcluster = 1`.

> 2017/10/27:

 + Version 0.0.4 is released!
 + scImpute now supports multi-code parallelism.
 
> 2017/10/22:

 + Version 0.0.3 is released!
 + Estimation of dropout probabilities is more accurate.
 + Imputation step is more robust.
 + `scimpute()` incorporates a new parameter `Kcluster` to specify the number of cell subpopulations.
 + `scImpute` is now able to detect outlier cells.
 
> 2017/07/01: 
  
  + Version 0.0.2 is released! 
  + This version speeds up the first step in `scImpute` and program now completes  in a few seconds when applied to a dataset with 10,000 genes and 100 cells (using single core).